SELECT
B.BÝLETID,
Y.ADSOY,
Y.ÜLKE,
Y.CÝNSÝYET,
B.BÝLETSINIFI,
B.BÝLETÜCRETÝ,
U.KALIÞHAVAALANI,
U.VARIÞHAVAALANI,
B.SATINALMATARÝHÝ,
Y.DOÐUMTARÝHÝ,
U.KALKIÞZAMANI,
U.VARIÞZAMANI,
U.UÇAKTÝPÝ,
U.STATÜ,
R.GEÇÝKMENEDENÝ,
R.GEÇÝKMEDAKÝKASI
FROM BÝLETLER B
JOIN YOLCULAR Y ON B.YOLCUID=Y.YOLCUID
JOIN UÇUÞLAR U ON  B.UÇUÞID=U.UÇUÞID
JOIN RÖTARLAR R ON B.UÇUÞID=R.UÇUÞID
ORDER BY B.BÝLETID ASC



