SELECT
B.BÝLETID,
B.BÝLETSINIFI,
B.BÝLETÜCRETÝ,
U.KALIÞHAVAALANI,
U.VARIÞHAVAALANI,
Y.ADSOY,
Y.ÜLKE
FROM BÝLETLER B
JOIN YOLCULAR Y ON B.YOLCUID=Y.YOLCUID
JOIN UÇUÞLAR U ON B.UÇUÞID=U.UÇUÞID
ORDER BY B.BÝLETID ASC