CREATE TABLE FLIGHTS(
FLIGHTID INT PRIMARY KEY,
DEPARTUREAÝRPORT VARCHAR(10),
ARRÝVALAÝRPART VARCHAR(10),
DEPARTURETIME DATETIME,
ARRIVALTIME DATETIME,
AIRCRAFTTYPE VARCHAR(20),
STATUSS VARCHAR(20));