SELECT UÇUÞID,
SUM(CASE WHEN BÝLETSINIFI = 'Economy' THEN 1 ELSE 0 END) AS EKONOMÝSAYISI,
SUM(CASE WHEN BÝLETSINIFI = 'Business' THEN 1 ELSE 0 END) AS BUSÝNESSAYISI
FROM BÝLETLER
GROUP BY UÇUÞID
ORDER BY UÇUÞID ASC
