SELECT ADSOY, ÜLKE, DOÐUMTARÝHÝ, CÝNSÝYET, 
CASE 
WHEN DATEDIFF(YEAR, DOÐUMTARÝHÝ, GETDATE()) < 30 THEN 'GENÇ'
WHEN DATEDIFF(YEAR, DOÐUMTARÝHÝ, GETDATE()) BETWEEN 30 AND 59 THEN 'ORTA'
ELSE 'YASLI'
END AS YASGRUBI
FROM YOLCULAR