WITH ULKEADI AS(
SELECT U.UÇUÞID, 
COUNT(DISTINCT Y.ÜLKE) AS MÝLLETSAYISI
FROM BÝLETLER B
JOIN YOLCULAR Y ON B.YOLCUID=Y.YOLCUID
JOIN UÇUÞLAR U ON B.UÇUÞID=U.UÇUÞID
GROUP BY U.UÇUÞID)
ORDER BY MÝLLETSAYISI ASC