WITH YOLCUÖDEMELERÝ AS (
SELECT YOLCUID,
SUM(BÝLETÜCRETÝ) AS TOPLAMÖDEME
FROM BÝLETLER
GROUP BY YOLCUID
)
SELECT Y.ADSOY, YY.TOPLAMÖDEME
FROM YOLCUÖDEMELERÝ YY
JOIN YOLCULAR Y ON YY.YOLCUID=Y.YOLCUID

ORDER BY TOPLAMÖDEME ASC