WITH KYÖDEME AS(
SELECT
YOLCUID,
SUM(BÝLETÜCRETÝ) AS KÖDEEME
FROM BÝLETLER
GROUP BY YOLCUID
HAVING SUM(BÝLETÜCRETÝ) > 5000
)

SELECT Y.ADSOY, KY.KÖDEEME
FROM KYÖDEME KY
JOIN YOLCULAR Y ON KY.YOLCUID=Y.YOLCUID

ORDER BY KÖDEEME DESC